# Makefile to get rid of old executables and logs
EXEC=compare\
	compare_3418\
	compare_ntcip\
	ix_byte_count\
	phases\
	rcv_ix_msg\
	rd3418\
	rd34182\
	rdntcip\
	rdntcip2\
	rdsniff\
	rdsniff_page\
	rdsniff_rfs\
	sendMsg2tlab\
	sendatsc2tlab\
	snd_ix_msg\
	test_page\
	test_rfs\
	testsniff
clean:
	rm -f *.log *.out $(EXEC)
